version: '2'

services:
  front:
    build:
      context: .
      dockerfile: Front
    image: shadash-mailu-front:latest
    restart: always
    env_file: mailu.env
    logging:
      driver: $LOG_DRIVER
    ports:
      - "$BIND_ADDRESS4:80:80"
      - "$BIND_ADDRESS4:443:443"
      - "$BIND_ADDRESS4:110:110"
      - "$BIND_ADDRESS4:143:143"
      - "$BIND_ADDRESS4:993:993"
      - "$BIND_ADDRESS4:995:995"
      - "$BIND_ADDRESS4:25:25"
      - "$BIND_ADDRESS4:465:465"
      - "$BIND_ADDRESS4:587:587"
      - "$BIND_ADDRESS6:80:80"
      - "$BIND_ADDRESS6:443:443"
      - "$BIND_ADDRESS6:110:110"
      - "$BIND_ADDRESS6:143:143"
      - "$BIND_ADDRESS6:993:993"
      - "$BIND_ADDRESS6:995:995"
      - "$BIND_ADDRESS6:25:25"
      - "$BIND_ADDRESS6:465:465"
      - "$BIND_ADDRESS6:587:587"
    volumes:
      - letsencrypt:/letsencrypt-root
      - "$ROOT/overrides/nginx:/overrides:ro"
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "$ROOT/redis:/data"
  imap:
    image: mailu/dovecot:$VERSION
    restart: always
    env_file: mailu.env
    volumes:
      - "$ROOT/mail:/mail"
      - "$ROOT/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
  smtp:
    image: mailu/postfix:$VERSION
    restart: always
    env_file: mailu.env
    volumes:
      - "$ROOT/mailqueue:/queue"
      - "$ROOT/overrides/postfix:/overrides:ro"
    depends_on:
      - front
  antispam:
    image: mailu/rspamd:$VERSION
    restart: always
    env_file: mailu.env
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim:ro"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
  fetchmail:
    image: mailu/fetchmail:$VERSION
    restart: always
    env_file: mailu.env
volumes:
  letsencrypt:
    driver: local
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $SUBNET
