version: '2'

services:
  front:
    image: mailutest/nginx:pr-1421
    restart: always
    env_file: mailu.env
    logging:
      driver: $LOG_DRIVER
    ports:
      - 0.0.0.0:8080:80
      - 0.0.0.0:4430:443
      - 0.0.0.0:110:110
      - 0.0.0.0:143:143
      - 0.0.0.0:993:993
      - 0.0.0.0:995:995
      - 0.0.0.0:25:25
      - 0.0.0.0:465:465
      - 0.0.0.0:587:587
    volumes:
      - $ROOT/overrides/nginx:/overrides:ro
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - $ROOT/redis:/data
  imap:
    image: mailutest/dovecot:pr-1421
    restart: always
    env_file: mailu.env
    volumes:
      - $ROOT/mail:/mail"
      - $ROOT/overrides/dovecot:/overrides:ro
    depends_on:
      - front
  smtp:
    image: mailutest/postfix:pr-1421
    restart: always
    env_file: mailu.env
    volumes:
      - $ROOT/mailqueue:/queue
      - $ROOT/overrides/postfix:/overrides:ro
    depends_on:
      - front
  antispam:
    image: mailutest/rspamd:pr-1421
    restart: always
    env_file: mailu.env
    volumes:
      - $ROOT/filter:/var/lib/rspamd
      - $ROOT/dkim:/dkim:ro
      - $ROOT/overrides/rspamd:/etc/rspamd/override.d:ro
    depends_on:
      - front
  antivirus:
    image: mailutest/clamav:pr-1421
    restart: always
    env_file: mailu.env
    volumes:
      - $ROOT/filter:/data
  webdav:
    image: mailutest/radicale:arm64-pr-1421
    restart: always
    env_file: mailu.env
    volumes:
      - $ROOT/dav:/data
  admin:
    image: mailutest/admin:pr-1421
    restart: always
    env_file: mailu.env
    volumes:
      - $ROOT/data:/data
      - $ROOT/dkim:/dkim
    depends_on:
      - redis
  webmail:
    image: mailutest/rainloop:pr-1421
    restart: always
    env_file: mailu.env
    volumes:
      - $ROOT/webmail:/data
    depends_on:
      - imap
  fetchmail:
    image: mailutest/fetchmail:pr-1421
    restart: always
    env_file: mailu.env
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $SUBNET
