version: '3.7'

services:
  mysql:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - $NEXTCLOUD_PATH/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - nextcloud-net
  nextcloud:
    image: nextcloud:fpm
    volumes:
      - $NEXTCLOUD_PATH/web:/var/www/html
    environment:
      - MYSQL_HOST=mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
    networks:
      - nextcloud-net
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/includes:/etc/nginx/includes
      - letsencrypt:/etc/letsencrypt
      - nginx_log:/var/log/nginx
      - ./letsencrypt/production_public:/data/letsencrypt
      - $NEXTCLOUD_PATH/web:/var/www/html
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nextcloud-net
volumes:
  letsencrypt:
    driver: local
  nginx_log:
    driver: local
networks:
  nextcloud-net:
    driver: bridge