version: '3.7'

services:
  mysql:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - $NEXTCLOUD_PATH/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - nextcloud-net
  nextcloud:
    image: nextcloud:fpm
    volumes:
      - $NEXTCLOUD_PATH/web:/var/www/html
    environment:
      - MYSQL_HOST=mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    depends_on:
      - mysql
    networks:
      - nextcloud-net
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/includes:/etc/nginx/includes
      - letsencrypt:/etc/letsencrypt
      - nginx_log:/var/log/nginx
      - ./letsencrypt/production_public:/data/letsencrypt
      - $NEXTCLOUD_PATH/web:/var/www/html
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - 80:80
      - 443:443
      - 110:110
      - 143:143
      - 993:993
      - 995:995
      - 25:25
      - 465:465
      - 587:587
    networks:
      - nextcloud-net
  synapse:
    image: matrixdotorg/synapse:3af9bb7198c64c6e6001b96cbfadc0bc2123d318-multiarch
    container_name: synapse
    volumes:
      - $NEXTCLOUD_PATH/synapse:/data
      - ./synapse/homeserver.yaml:/data/homeserver.yaml
      - ./synapse/synapse.sophiahadash.nl.signing.key:/data/synapse.sophiahadash.nl.signing.key
      - $NEXTCLOUD_PATH/mautrix-whatsapp/registration.yaml:/data/bridges/whatsapp/registration.yaml:ro
    healthcheck:
      test: [ "CMD", "curl", "-fSs", "http://localhost:8008/health" ]
      interval: 1m
      timeout: 10s
      retries: 3
    restart: always
    depends_on:
      - synapse-postgresql
    networks:
      - nextcloud-net
  synapse-postgresql:
    image: postgres:9.6.19
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: $SYNAPSE_POSTGRESS_PASSWORD
      POSTGRES_USER: synapse
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - $NEXTCLOUD_PATH/synapse-postgres:/var/lib/postgresql/
    networks:
      - nextcloud-net
  synapse-bridge-whatsapp:
    image: dock.mau.dev/tulir/mautrix-whatsapp:00966626857b694aba78f4d40ae0a048f8da3ae4-amd64
    volumes:
      - $NEXTCLOUD_PATH/mautrix-whatsapp:/data:z
      - ./synapse/whatsapp/config.yaml:/data/config.yaml
    restart: always
    networks:
      - nextcloud-net
  rsnapshot:
    build:
      context: ./rsnapshot-docker
      dockerfile: Dockerfile
    image: shadash-rsnapshot-docker:latest
    volumes:
      - $BACKUP_PATH:/backup
      - $NEXTCLOUD_PATH:/data
    environment:
      - BACKUP_NAME=nextcloud
      - BACKUP_SOURCE=/data
      - BACKUP_HOURLY=0
      - BACKUP_DAILY=3
      - BACKUP_WEEKLY=3
      - BACKUP_MONTHLY=3
      - BACKUP_YEARLY=3
      - CRON_DAILY=0 3 * * *
      - CRON_WEEKLY=30 3 * * 0
      - CRON_MONTHLY=0 4 1 * *
      - CRON_YEARLY=0 5 1 1 *
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - nextcloud-net
volumes:
  letsencrypt:
    driver: local
  nginx_log:
    driver: local
networks:
  nextcloud-net:
    driver: bridge