version: "3.7"

services:
  letsencrypt-renew:
    image: clover/certbot:latest
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt-lib:/var/lib/letsencrypt
      - letsencrypt-log:/var/log/letsencrypt
      - ./production_public:/data/letsencrypt
    command: ["certbot", "renew", "--webroot",  "-w", "/data/letsencrypt"]
    networks:
      - letsencrypt-net
volumes:
  letsencrypt:
    driver: local
  letsencrypt-lib:
    driver: local
  letsencrypt-log:
    driver: local
networks:
  letsencrypt-net:
    driver: bridge